### ISSUE TITLE
Ideas for improvement

### ISSUE THREAD

**Issue by abdeladim-s** [twinlizzie/Sylvie-2023#1]
wow Great project @twinlizzie, You are very talented. Good job :clap: 

So I have watched the demo and I believe the conversation can get faster (especially with this hardware specs), but I am not sure where is the bottleneck! 
I took a look at the [code](https://github.com/twinlizzie/Sylvie-2023/blob/e4736dcc190b4868a441299e9c4c41d88a4af73f/python/conversation/llama/play_tts_llama.py), I have some ideas:

1- For STT, you are using `KaldiRecognizer`  but I think there are better options now. Are you not aware of [whisper.cpp](https://github.com/ggerganov/whisper.cpp) ? Please take a look at the `asssistance` example on my repo [pywhispercpp](https://github.com/abdeladim-s/pywhispercpp#assistant), I've got good results with near real time performance. Give it a try and compare it with  `KaldiRecognizer` and keep whichever gives you good fast results. 

2- For the language model, Did you try the version `2.2.0`  of `pyllamacpp` with old models? I think you will get good results with it. The newest commits of `llama.cpp` are not stable yet. I didn't notice any big hullicination problem with that old version at least. 
Also you can add the prompt_prefix/suffix to the model instanciation (See how I did it in [here](https://github.com/abdeladim-s/pyllamacpp/blob/main/pyllamacpp/cli.py)). 
I would also suggest to try different language models, `alpaca` is great, you can try `gpt4all` as well. 

3- For the TTS, `tartoise` is the best in terms of the quality, but have you measured how much time the inference is taking ? I think there are faster models with good quality/inference time , try for example [tacotron2](https://github.com/NVIDIA/tacotron2) or [FastSpeechs](https://github.com/ming024/FastSpeech2), there are also many more out there faster than `tartoise`.

4- Another idea is, instead of waiting the entire generation of the language model to finish and then send it to TTS, why not for example take a number of tokens (let us say for example a batch of 4 words) and then spawn a separate thread to run the TTS, meanwhile get the new batch from the language model and repeat the same .. I think if you get the time right, the user won't notice and you will get near real time conversation ? 

I wish I can test those ideas to help you out but unfortunately it is not easy to replicate the same hardware :sweat_smile: 
But feel free to let me know if you need help!

**Comment by twinlizzie** [comment]
> wow Great project @twinlizzie, You are very talented. Good job clap
> 
> So I have watched the demo and I believe the conversation can get faster (especially with this hardware specs), but I am not sure where is the bottleneck! I took a look at the [code](https://github.com/twinlizzie/Sylvie-2023/blob/e4736dcc190b4868a441299e9c4c41d88a4af73f/python/conversation/llama/play_tts_llama.py), I have some ideas:
> 
> 1- For STT, you are using `KaldiRecognizer` but I think there are better options now. Are you not aware of [whisper.cpp](https://github.com/ggerganov/whisper.cpp) ? Please take a look at the `asssistance` example on my repo [pywhispercpp](https://github.com/abdeladim-s/pywhispercpp#assistant), I've got good results with near real time performance. Give it a try and compare it with `KaldiRecognizer` and keep whichever gives you good fast results.
> 
> 2- For the language model, Did you try the version `2.2.0` of `pyllamacpp` with old models? I think you will get good results with it. The newest commits of `llama.cpp` are not stable yet. I didn't notice any big hullicination problem with that old version at least. Also you can add the prompt_prefix/suffix to the model instanciation (See how I did it in [here](https://github.com/abdeladim-s/pyllamacpp/blob/main/pyllamacpp/cli.py)). I would also suggest to try different language models, `alpaca` is great, you can try `gpt4all` as well.
> 
> 3- For the TTS, `tartoise` is the best in terms of the quality, but have you measured how much time the inference is taking ? I think there are faster models with good quality/inference time , try for example [tacotron2](https://github.com/NVIDIA/tacotron2) or [FastSpeechs](https://github.com/ming024/FastSpeech2), there are also many more out there faster than `tartoise`.
> 
> 4- Another idea is, instead of waiting the entire generation of the language model to finish and then send it to TTS, why not for example take a number of tokens (let us say for example a batch of 4 words) and then spawn a separate thread to run the TTS, meanwhile get the new batch from the language model and repeat the same .. I think if you get the time right, the user won't notice and you will get near real time conversation ?
> 
> I wish I can test those ideas to help you out but unfortunately it is not easy to replicate the same hardware sweat_smile But feel free to let me know if you need help!

Hi there!

Thanks for the feedback.

Yes, indeed - I am currently in the process of trying to speed up the code. I've been looking into everything from Cython, to PyPy, but there doesn't seem to be a reliable way of implementing it with all the modules I have imported.

The whole idea of using Tortoise-TTS is to get realistic speech with intonation, breathing and sounds like 'um, ahhh, ehhh,'. Tortoise-TTS-Fast comes with much better performance and even better results.

Tortoise-TTS is not the problem - the only bottlenecks now are the python bindings for Llama.cpp. Because llama.cpp is supposed to be fast, but running it on python slows it down 10x. Which is a bit of a shame. 

If only I had the skill to write it all in C - none of this would be a problem. :)

**Comment by abdeladim-s** [comment]
I don't think the Python bindings slow down `llama.cpp` by 10x because all the computation is still performed in the cpp side .. certainly there is an overhead from the Python interpreter, but not 10x, at least not on my tests. If it is the case on your side, and `llama.cpp` is running faster than the bindings, maybe you will need to compile the bindings from source.

Vosk is not the only one that works offline, `whisper` works offline as well. 

Yes upgrading the RAM to 32GB is a good idea. It will make your life easier.

**Comment by twinlizzie** [comment]
True. It could just be the case that there's too many models being loaded at the same time.

Time to buy more RAM.

**Comment by abdeladim-s** [comment]
Yeah, probably. 
Adding more RAM will help in any case. 

Good luck :+1:
